"""Shared pytest fixtures for the PyDLNM test suite."""

import numpy as np
import pytest
from r_compat_helpers import _fixtures_present, load_fixture_vector


@pytest.fixture(scope="session")
def synthetic_x():
    """200-element exposure vector generated by R set.seed(42)."""
    if not _fixtures_present("synthetic_x.csv"):
        pytest.skip("R fixtures not generated; run tests/fixtures/generate_fixtures.R")
    return load_fixture_vector("synthetic_x.csv")


@pytest.fixture(scope="session")
def coef_12():
    """Fixed 12-element coefficient vector from R fixtures."""
    if not _fixtures_present("coef_12.csv"):
        pytest.skip("R fixtures not generated; run tests/fixtures/generate_fixtures.R")
    return load_fixture_vector("coef_12.csv")


@pytest.fixture(scope="session")
def vcov_12():
    """Diagonal 12x12 vcov matrix (diag * 0.0001)."""
    return np.eye(12) * 0.0001
