"""R compatibility tests for pydlnm basis functions.

Each test loads a pre-computed fixture generated by R's dlnm package and
asserts element-wise equality (within floating-point tolerance) against the
PyDLNM implementation.

Fixtures are generated by running:
    Rscript tests/fixtures/generate_fixtures.R

Tests are automatically skipped when fixture files are absent, so CI passes
even before fixtures have been committed.
"""

import numpy as np
import pytest

import pydlnm
from r_compat_helpers import FIXTURES_DIR, load_fixture_matrix, load_fixture_vector, require_fixtures

# ---------------------------------------------------------------------------
# Tolerance — match R to ~6 significant figures (double precision round-trip)
# ---------------------------------------------------------------------------
RTOL = 1e-5
ATOL = 1e-9


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _check(py_mat: np.ndarray, r_csv: str) -> None:
    """Compare a Python basis matrix against the R golden fixture."""
    r_mat = (
        load_fixture_vector(r_csv).reshape(-1, 1)
        if py_mat.ndim == 1
        else load_fixture_matrix(r_csv)
    )
    np.testing.assert_allclose(
        py_mat,
        r_mat,
        rtol=RTOL,
        atol=ATOL,
        err_msg=f"Mismatch vs R fixture '{r_csv}'",
    )


# ---------------------------------------------------------------------------
# Natural splines — ns
# ---------------------------------------------------------------------------


class TestNsBasis:
    @require_fixtures("synthetic_x.csv", "onebasis_ns_df4.csv")
    def test_ns_df4(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="ns", df=4)
        _check(np.asarray(ob), "onebasis_ns_df4.csv")

    @require_fixtures("synthetic_x.csv", "onebasis_ns_df4_intercept.csv")
    def test_ns_df4_intercept(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="ns", df=4, intercept=True)
        _check(np.asarray(ob), "onebasis_ns_df4_intercept.csv")

    @require_fixtures("synthetic_x.csv", "onebasis_ns_knots.csv")
    def test_ns_explicit_knots(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="ns", knots=np.array([15.0, 20.0, 25.0]))
        _check(np.asarray(ob), "onebasis_ns_knots.csv")

    def test_ns_shape(self, synthetic_x):
        """Shape invariant: df columns regardless of fixture availability."""
        ob = pydlnm.onebasis(synthetic_x, fun="ns", df=4)
        assert ob.shape == (len(synthetic_x), 4)

    def test_ns_shape_intercept(self, synthetic_x):
        # ns(df=4, intercept=True): df counts include the intercept, so still 4 cols
        ob = pydlnm.onebasis(synthetic_x, fun="ns", df=4, intercept=True)
        assert ob.shape == (len(synthetic_x), 4)


# ---------------------------------------------------------------------------
# B-splines — bs
# ---------------------------------------------------------------------------


class TestBsBasis:
    @require_fixtures("synthetic_x.csv", "onebasis_bs_df5.csv")
    def test_bs_df5(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="bs", df=5)
        _check(np.asarray(ob), "onebasis_bs_df5.csv")

    def test_bs_shape(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="bs", df=5)
        assert ob.shape == (len(synthetic_x), 5)


# ---------------------------------------------------------------------------
# Linear — lin
# ---------------------------------------------------------------------------


class TestLinBasis:
    @require_fixtures("synthetic_x.csv", "onebasis_lin.csv")
    def test_lin(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="lin")
        _check(np.asarray(ob), "onebasis_lin.csv")

    def test_lin_is_identity(self, synthetic_x):
        """lin basis is just x, no fixture needed."""
        ob = pydlnm.onebasis(synthetic_x, fun="lin")
        np.testing.assert_array_equal(ob[:, 0], synthetic_x)


# ---------------------------------------------------------------------------
# Polynomial — poly
# ---------------------------------------------------------------------------


class TestPolyBasis:
    @require_fixtures("synthetic_x.csv", "onebasis_poly_deg2.csv")
    def test_poly_deg2(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="poly", degree=2)
        _check(np.asarray(ob), "onebasis_poly_deg2.csv")

    def test_poly_shape(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="poly", degree=2)
        assert ob.shape == (len(synthetic_x), 2)  # degrees 1 and 2 (no intercept)


# ---------------------------------------------------------------------------
# Threshold — thr
# ---------------------------------------------------------------------------


class TestThrBasis:
    @require_fixtures("synthetic_x.csv", "onebasis_thr_h.csv")
    def test_thr_high(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="thr", thr_value=20.0, side="h")
        _check(np.asarray(ob), "onebasis_thr_h.csv")

    @require_fixtures("synthetic_x.csv", "onebasis_thr_l.csv")
    def test_thr_low(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="thr", thr_value=20.0, side="l")
        _check(np.asarray(ob), "onebasis_thr_l.csv")

    @require_fixtures("synthetic_x.csv", "onebasis_thr_d.csv")
    def test_thr_double(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="thr", thr_value=np.array([15.0, 25.0]), side="d")
        _check(np.asarray(ob), "onebasis_thr_d.csv")

    def test_thr_high_non_negative(self, synthetic_x):
        """thr 'h' must be non-negative everywhere."""
        ob = pydlnm.onebasis(synthetic_x, fun="thr", thr_value=20.0, side="h")
        assert np.all(np.asarray(ob) >= 0)

    def test_thr_low_non_negative(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="thr", thr_value=20.0, side="l")
        assert np.all(np.asarray(ob) >= 0)


# ---------------------------------------------------------------------------
# Strata
# ---------------------------------------------------------------------------


class TestStrataBasis:
    @require_fixtures("synthetic_x.csv", "onebasis_strata_df3.csv")
    def test_strata_df3(self, synthetic_x):
        ob = pydlnm.onebasis(synthetic_x, fun="strata", df=3)
        _check(np.asarray(ob), "onebasis_strata_df3.csv")

    def test_strata_is_indicator(self, synthetic_x):
        """All entries must be 0 or 1; reference-category rows sum to 0, others to 1."""
        ob = pydlnm.onebasis(synthetic_x, fun="strata", df=3)
        mat = np.asarray(ob)
        assert np.all((mat == 0) | (mat == 1))
        row_sums = mat.sum(axis=1)
        assert np.all((row_sums == 0) | (row_sums == 1))


# ---------------------------------------------------------------------------
# Integer
# ---------------------------------------------------------------------------


class TestIntegerBasis:
    @require_fixtures("onebasis_integer_lagseq.csv")
    def test_integer_lagseq(self):
        lag_seq = np.arange(0, 11, dtype=float)
        ob = pydlnm.onebasis(lag_seq, fun="integer")
        r_mat = load_fixture_matrix("onebasis_integer_lagseq.csv")
        np.testing.assert_allclose(np.asarray(ob), r_mat, rtol=RTOL, atol=ATOL)

    def test_integer_is_indicator(self):
        lag_seq = np.arange(0, 5, dtype=float)
        ob = pydlnm.onebasis(lag_seq, fun="integer")
        mat = np.asarray(ob)
        assert np.all((mat == 0) | (mat == 1))
